Areas/Admin/ViewModels/ProductNewQuantity.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Suppliro.Areas.Admin.ViewModels
{
    public class ProductNewQuantity
    {
        public string strProductName { get; set; }
        public int iSupplierOrderID { get; set; }
        public int iSupplierOrderLineID { get; set; }
        public int iProductQuantity { get; set; }
    }
}

Areas/Admin/ViewModels/SupplierOrderProductReplaceViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Suppliro.Entities;

namespace Suppliro.Areas.Admin.ViewModels
{
    public class SupplierOrderProductReplaceViewModel
    {
        public int iSupplierOrderID { get; set; }
        public int iProductID { get; set; }
        public string strProductCode { get; set; }
        public int iSupplierOrderLineID { get; set; }
        public int iSelectedProductCategory { get; set; }
        public List<Category> lstProductCategoryList { get; set; }
        public int iSelectedProduct { get; set; }
        public List<Product> lstProductList { get; set; }
        [Range(0, int.MaxValue, ErrorMessage = "The input should be a positive value.")]
        public int iQuantity { get; set; }
    }
}

Areas/Admin/ViewModels/SupplierOrderViewModel.cs
using Suppliro.Entities;
using System;
using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;

namespace Suppliro.Areas.Admin.ViewModels
{
    public class SupplierOrderViewModel
    {
        public SupplierOrder SupplierOrder { get; set; }
        public List<SupplierOrderLineEdited> lstSupplierOrderLinesAdded { get; set; }
        public List<SupplierOrderLineEdited> lstSupplierOrderLinesChanged { get; set; }
        public List<SupplierOrderLineEdited> lstSupplierOrderLinesRemoved { get; set; }
    }
}

Areas/Admin/ViewModels/SupplierOrdersViewModel.cs
using Suppliro.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Suppliro.Areas.Admin.ViewModels
{
    public class SupplierOrdersViewModel
    {
        public List<Supplier> SuppliersWithOpenOrders { get; set; }

        public List<Supplier> SupplierOrdersToday { get; set; }
    }
}

Entities/Order.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Suppliro.Entities
{
    public class Order
    {
        [Key]
        public int Id { get; set; }

        public string OrderNumber { get; set; }

        public DateTime DatePlaced { get; set; }

        public double SubTotal { get; set; }

        public double VATAmount { get; set; }

        public double Total { get; set; }

        //We have company information for this particular order as details of a company may change
        public string UserId { get; set; }        

        public bool IsComplete { get; set; }

        public DateTime? DateCompleted { get; set; }

        public bool IsInvoiced { get; set; }

        public double PercentageComplete { get; set; }

        public int CustomerId { get; set; }

        public string CustomerName { get; set; }

        public virtual Customer Customer { get; set; }

        [Display(Name = "Trading Name")]
        public string TradingName { get; set; }

        [Display(Name = "Registered Name")]
        public string RegisteredName { get; set; }

        [Display(Name = "VAT Number")]
        public string VATNumber { get; set; }

        [Display(Name = "Tel Number")]
        public string TelNumber { get; set; }

        [Display(Name = "Buyer Name")]
        public string BuyersName { get; set; }

        [Display(Name = "Buyer ID")]
        public string BuyersIDNumber { get; set; }

        [Display(Name = "Email")]
        public string EmailAddress { get; set; }

        #region Physical Address
        [Display(Name = "Physical Address")]
        public string PhysicalAddress1 { get; set; }

        public string PhysicalAddress2 { get; set; }

        [Display(Name = "Postal Code")]
        public string PhysicalPostalCode { get; set; }

        [Display(Name = "Region")]
        public string PhysicalRegion { get; set; }

        [Display(Name = "City")]
        public string PhysicalTown { get; set; }
        #endregion

        public bool Edited { get; set; }
        public List<OrderLine> OrderLines { get; set; }
    }
}

Entities/SupplierOrder.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Suppliro.Entities
{
    public class SupplierOrder
    {
        [Key]
        public int Id { get; set; }

        public int SupplierId { get; set; }

        public string SupplierEmails { get; set; }

        public Supplier Supplier { get; set; }

        public string OrderNumber { get; set; }

        public DateTime DateCreated { get; set; } 
        
        public bool IsEmailed { get; set; }

        public bool IsComplete { get; set; }
        
        public DateTime? DateMailed { get; set; }       

        public string SupplierInvoiceNumber { get; set; }

        public double? TotalValue { get; set; }

        public double? TotalMarkedupValue { get; set; }

        public DateTime? DateCompleted { get; set; }

        public List<SupplierOrderLine> SupplierOrderLines { get; set; }
        public List<SupplierOrderLineEdited> SupplierOrderLinesEdited { get; set; }
        public bool Edited { get; set; }
    }
}

ViewModels/SupplierOrder.cs
using Suppliro.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Suppliro.ViewModels
{
    public class SupplierOrder
    {
        public Supplier Supplier { get; set; }

        public List<Order> Orders { get; set; }
    }
}

Areas/Admin/Controllers/SupplierOrderController.cs
using Suppliro.Areas.Admin.Manager;
using Suppliro.Areas.Admin.ViewModels;
using Suppliro.Context;
using Suppliro.Search;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Suppliro.Entities;
using System.ComponentModel.DataAnnotations;
using Suppliro.Data;
using Suppliro.Manager;
using Suppliro.Areas.Admin.Data;

namespace Suppliro.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class SupplierOrderController : Controller
    {
        // GET: Admin/SupplierOrder
        public ActionResult Index()
        {
            SupplierOrderManager mgr = new SupplierOrderManager(new DBContext());
            return View(mgr.GetSupplierOrdersPlacedToday());
        }

        public ActionResult History()
        {
            SupplierOrderManager mgr = new SupplierOrderManager(new DBContext());
            return View(mgr.GetSupplierOrdersExceptToday());
        }

        /// <summary>
        /// Returns the supplier order 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Order(int id)
        {
            SupplierOrderManager mgr = new SupplierOrderManager(new DBContext());
            var model = mgr.GetSupplierOrderById(id);
            if (model == null)
                return RedirectToAction("Index");

            return View("~/Areas/Admin/Views/SupplierOrder/Order.cshtml", model);
        }

        [HttpGet]
        public ActionResult GetSearchPartial(string id, string name)
        {
            ProductReplaceViewModel vm = new ProductReplaceViewModel
            {
                ProductId = Int32.Parse(id),
                ProductCode = name
            };
            return PartialView("~/Areas/Admin/Views/SupplierOrder/_SupplierOrderProductSearch.cshtml", vm);
        }

        [HttpGet]
        public ActionResult GetSupplierOrderProductReplacePartial(int iProductID, string strProductName, int iSupplierOrderLineID, int iSupplierOrderID)
        {
            SupplierOrderProductReplaceViewModel SupplierOrderProductReplaceViewModel = new SupplierOrderProductReplaceViewModel()
            {
                iProductID = iProductID,
                strProductCode = strProductName,
                iSupplierOrderLineID = iSupplierOrderLineID,
                iSupplierOrderID = iSupplierOrderID
            };

            CategoryManager cmgr = new CategoryManager(new DBContext());
            ProductManager pmgr = new ProductManager(new DBContext());

            //Get all product categories
            SupplierOrderProductReplaceViewModel.lstProductCategoryList = cmgr.GetAll();
            //Get all products by first category
            SupplierOrderProductReplaceViewModel.lstProductList = pmgr.GetAllProductsByCategoryId(SupplierOrderProductReplaceViewModel.lstProductCategoryList[0].Id);
            foreach (var item in SupplierOrderProductReplaceViewModel.lstProductList)
            {
                if (item.Supplier.TradingName != null)
                    item.DisplayName = item.Code + ": " + item.Supplier.TradingName;
                else
                    item.DisplayName = item.Code + ": ";
            }

            return PartialView("~/Areas/Admin/Views/SupplierOrder/SupplierOrderProductReplace.cshtml", SupplierOrderProductReplaceViewModel);
        }

        [HttpPost]
        public ActionResult SupplierOrderProductReplace(SupplierOrderProductReplaceViewModel SupplierOrderProductReplaceViewModel)
        {
            int x = 2;
            return null;
            //return PartialView("~/Areas/Admin/Views/SupplierOrder/SupplierOrderProductReplace.cshtml", SupplierOrderProductReplaceViewModel);
        }
        [HttpPost]
        public ActionResult ProductReplaceCategoryChange(int iSelectedProductCategory)
        {
            if (iSelectedProductCategory != 0)
            {
                ProductManager pmgr = new ProductManager(new DBContext());

                //Get all products by category
                List<Product> lstProducts = new List<Product>();
                lstProducts = pmgr.GetAllProductsByCategoryId(iSelectedProductCategory);
                foreach (var item in lstProducts)
                {
                    if (item.Supplier.TradingName != null)
                        item.DisplayName = item.Code + ": " + item.Supplier.TradingName;
                    else
                        item.DisplayName = item.Code + ": ";
                }

                return Json(new { lstProducts = lstProducts }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(null);
            }
        }

        [HttpGet]
        public ActionResult GetProductNewQuantityPartial(int iSupplierOrderID, int iSupplierOrderLineID, string strProductName)
        {
            ProductNewQuantity ProductNewQuantity = new ProductNewQuantity();
            ProductNewQuantity.iSupplierOrderID = iSupplierOrderID;
            ProductNewQuantity.iSupplierOrderLineID = iSupplierOrderLineID;
            ProductNewQuantity.strProductName = strProductName;

            return PartialView("~/Areas/Admin/Views/SupplierOrder/ProductNewQuantity.cshtml", ProductNewQuantity);
        }

        [HttpGet]
        public ActionResult GetSupplierOrderView(int supplierOrderID)
        {
            ViewBag.supplierOrderID = supplierOrderID;

            SupplierOrderManager mgr = new SupplierOrderManager(new DBContext());
            var model = mgr.GetSupplierOrderById(supplierOrderID);
            if (model == null)
                return RedirectToAction("Index");

            return PartialView("~/Areas/Admin/Views/SupplierOrder/SupplierOrderView.cshtml");
        }

        public void ProductNewQuantity(ProductNewQuantity ProductNewQuantity)
        {
            if (ProductNewQuantity.iProductQuantity > 0)
            {
                DBContext _db = new DBContext();
                SupplierOrderLineEdited SupplierOrderLineEdited = null;
                OrderLineEdited OrderLineEdited = null;

                SupplierOrderData SupplierOrderData = new SupplierOrderData(_db);
                OrderData OrderData = new OrderData(_db);
                OrderManager OrderManager = new OrderManager(_db);
                SupplierOrderManager SupplierOrderManager = new SupplierOrderManager(_db);
                InvoiceManager invMgr = new InvoiceManager(_db);

                //Get supplier order line quantity
                var supplierOrderLine = SupplierOrderData.GetSupplierOrderLineById(ProductNewQuantity.iSupplierOrderLineID);
                //Check if supplier order line edited exists for quantity change, if not, create new supplier order line edited 
                //Get supplier Order line edited
                SupplierOrderLineEdited = SupplierOrderData.GetSupplierOrderLineEditedBySupplierOrderLineId(ProductNewQuantity.iSupplierOrderLineID);
                if (SupplierOrderLineEdited == null)
                {
                    SupplierOrderLineEdited = new SupplierOrderLineEdited()
                    {
                        SupplierOrderLineId = supplierOrderLine.Id,
                        SupplierOrderId = supplierOrderLine.SupplierOrderId,
                        OrderId = supplierOrderLine.OrderId,
                        OrderLineId = supplierOrderLine.OrderLineId,
                        OrderNumber = supplierOrderLine.OrderNumber,
                        CustomerId = supplierOrderLine.CustomerId,
                        CustomerName = supplierOrderLine.CustomerName,
                        ProductId = supplierOrderLine.ProductId,
                        ProductCode = supplierOrderLine.ProductCode,
                        ProductUnit = supplierOrderLine.ProductUnit,
                        ProductPrice = supplierOrderLine.ProductPrice,
                        Quantity = supplierOrderLine.Quantity,
                    };
                }
                if (SupplierOrderLineEdited.Quantity == ProductNewQuantity.iProductQuantity)
                    SupplierOrderLineEdited.QuantityEdited = false;
                else
                    SupplierOrderLineEdited.QuantityEdited = true;

                //Set new supplier order line quantity
                supplierOrderLine.Quantity = ProductNewQuantity.iProductQuantity;
                //save changes
                SupplierOrderData.SaveOrderLine(supplierOrderLine);
                SupplierOrderData.SaveOrderLineEdited(SupplierOrderLineEdited);
                //Update Order Supplier Total
                SupplierOrderManager.CalculateSupplierOrderTotals(supplierOrderLine.SupplierOrderId);

                //Get order line
                var orderLine = OrderData.GetOrderLineById(supplierOrderLine.OrderLineId);
                //Check if order line edited exists for quantity change, if not, create new supplier order line edited 
                //Get Order line edited
                OrderLineEdited = OrderData.GetOrderLineEditedByOrderLineId(supplierOrderLine.OrderLineId);
                if (OrderLineEdited == null)
                {
                    OrderLineEdited = new OrderLineEdited
                    {
                        OrderLineId = orderLine.Id,
                        ProductId = orderLine.ProductId,
                        OrderId = orderLine.OrderId,
                        ProductCode = orderLine.ProductCode,
                        SupplierId = orderLine.SupplierId,
                        SupplierTradingName = orderLine.SupplierTradingName,
                        UnitPrice = orderLine.UnitPrice,
                        Unit = orderLine.Unit,
                        Quantity = orderLine.Quantity,
                        Amount = orderLine.Amount,
                        VATAmount = orderLine.VATAmount,
                    };
                }

Areas/Admin/Views/SupplierOrder/Index.cshtml
@using Suppliro.Entities

@model List<SupplierOrder>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_layoutAdmin.cshtml";
}
<div id='orderView' class='modal fade in'>
    <div class="modal-dialog">
        <div class="modal-content">
            <div id='orderViewContent'></div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Supplier Orders</h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                @{
                    if (Model == null || Model.Count() == 0)
                    {
                        <div class="bs-example" data-example-id="simple-jumbotron">
                            <div class="jumbotron">
                                <h1>No Suppliers Orders Found</h1>
                            </div>
                        </div>
                    }
                    else
                    {
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>Trading Name</th>
                                    <th>Order Number</th>
                                    <th>Date Placed</th>
                                    <th>
                                        Date Completed
                                    </th>
                                    <th>
                                        Total Value
                                    </th>
                                    <th>
                                        Total Marked Up Value
                                    </th>
                                    <th>View</th>
                                    <th>Edit</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var ord in Model)
                                {
                                    <tr>
                                        <td>@ord.Supplier.TradingName</td>
                                        <td>@ord.OrderNumber</td>
                                        <td>@ord.DateCreated</td>
                                        <td>@ord.DateCompleted</td>
                                        <td>
                                            @ord.TotalValue
                                        </td>
                                        <td>
                                            @ord.TotalMarkedupValue
                                        </td>
                                        <td><a onclick="jsViewOrder(@ord.Id)" style="cursor:pointer;">View</a></td>
                                        <td>@Html.ActionLink("Edit", "Order", new { id = @ord.Id })</td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    }
                }
            </div>
        </div>
    </div>
</div>

@****SUBMIT ITEM****@
<script type="text/javascript">
    function jsViewOrder(id) {
        var supplierOrderID = id;

        var modalBody = $("#orderViewContent");

        $.ajax({
            url: '@Url.Action("GetSupplierOrderView", "SupplierOrder")',
            cache: false,
            type: "get",
            dataType: "html",
            data: { "supplierOrderID": supplierOrderID },
            success: function (result) {
                modalBody.empty();
                modalBody.append(result);
                $('#orderView').modal('show');
            }
        });
        }
</script>

Areas/Admin/Views/SupplierOrder/Order.cshtml
@using Suppliro.Entities

@model SupplierOrder

@{
    ViewBag.Title = "Order";
    Layout = "~/Areas/Admin/Views/Shared/_layoutAdmin.cshtml";
}

<div class="modal fade" id="modalReplace" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog">
        <div class="modal-content">
            <div id="modalReplaceContent" class="modal-body">
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div id='modalProduct' class='modal fade in'>
    <div class="modal-dialog">
        <div class="modal-content">
            <div id='modalProductContent'></div>
        </div>
    </div>
</div>

<div id='modalProductQuantity' class='modal fade in'>
    <div class="modal-dialog">
        <div class="modal-content">
            <div id='modalProductQuantityContent'></div>
        </div>
    </div>
</div>

<div class="col-md-12 col-sm-12 col-xs-12">
    <div class="x_panel">
        <div class="x_title">
            @Html.HiddenFor(Model => Model.Id)
            <h2>@Model.Supplier.TradingName</h2>
            <input type="button" id="btnProductAdd" class="btn btn-dark pull-right" value="Add Product" />
            <div class="clearfix"></div>
        </div>
        <div class="x_content">            
            <table class="table table-striped" id="Suppliers">
                <thead>
                    <tr>
                        <th>
                            Customer Name
                        </th>
                        <th>
                            Order Number
                        </th>
                        <th>
                            Product Code
                        </th>
                        <th>
                            Product Unit
                        </th>
                        <th>
                            Price
                        </th>
                        <th>
                            Qty
                        </th>
                        <th>
                            Quantity
                        </th>
                        <th>
                            Replace
                        </th>
                        <th>
                            Remove
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.SupplierOrderLines.Where(x => x.IsReplaced == false))
                    {
                        <tr id="@item.Id">
                            <td>
                                @item.CustomerName
                            </td>
                            <td>
                                @item.OrderNumber
                            </td>
                            <td class="item-name">@item.ProductCode</td>
                            <td>
                                @item.ProductUnit
                            </td>
                            <td>
                                @item.ProductPrice
                            </td>
                            <td>
                                @item.Quantity
                            </td>
                            <td style="width: 25px">
                                <input id="@item.Id" type="button" value="Quantity" class="btn btn-custom btn-sm btnQty" />
                            </td>
                            <td style="width: 25px">
                                <input id="@item.ProductId" type="button" value="Replace" class="btn btn-custom btn-sm atb" />
                            </td>
                            <td style="width: 25px">
                                <input id="@item.Id" type="button" value="Remove" class="btn btn-custom btn-rem atb" />
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

@section scripts
{

    <script type="text/javascript">

        $(function () {

            //ADD PRODUCT
            $(document).on('click', '#btnProductAdd', function (e) {
                var modalBody = $("#modalProductContent");

                $.ajax({
                    url: '@Url.Action("ProductAdd", "SupplierOrder")',
                    cache: false,
                    type: "get",
                    dataType: "html",
                    data: {"iSupplierOrderID": @Model.Id},
                    success: function (result) {
                        modalBody.empty();
                        modalBody.append(result);
                        $('#modalProduct').modal('show');
                    }
                });
            });

            //SUBMIT ADD PRODUCT
            $(document).on('submit', 'form', function (e) {
                e.preventDefault();
                var modalBody = $("#modalProductContent");
                var modal = $('#modalProduct');

                $.post(this.action, $(this).serialize(), function (response) {

                    modalBody.empty();
                    modal.modal('toggle');
                    window.location.href = "/Admin/SupplierOrder/Order/" + response.orderID.toString() + "/";

                }, 'json');
            });

            //EDIT QUANTITY
            $(".btnQty").click(function () {
                var trLineId = $(this).closest("tr").attr('id');

                var modalBody = $("#modalProductQuantityContent");
                var tr = $(this).closest("tr");
                var prodCode = tr.find(".item-name").html();
                var trLineId = $(this).closest("tr").attr('id');

                $.ajax({
                    url: '@Url.Action("GetProductNewQuantityPartial", "SupplierOrder")',
                    cache: false,
                    type: "get",
                    dataType: "html",
                    data: {"iSupplierOrderID": @Model.Id, iSupplierOrderLineID: trLineId, strProductName: prodCode},
                    success: function (result) {
                        modalBody.empty();
                        modalBody.append(result);
                        $('#modalProductQuantity').modal('show');
                    }
                });
            });

            //REPLACE PRODUCT
            $(".btn-sm.atb").click(function () {
                var modalBody = $("#modalReplaceContent");

                var tr = $(this).closest("tr");
                var trLineId = $(this).closest("tr").attr('id');
                var prodId = tr.find(".atb").attr('id');
                var modalBody = $("#modalReplaceContent");
                var prodCode = tr.find(".item-name").html();
                var iSupplierOrderID = @Model.Id;
                $(".modal-body").attr('id', tr.attr('id'));

                $.ajax({
                    url: "/SupplierOrder/GetSupplierOrderProductReplacePartial",
                    data: { iProductID: prodId, strProductName: prodCode, iSupplierOrderLineID: trLineId, iSupplierOrderID: iSupplierOrderID },
                    cache: false,
                    type: "get",
                    dataType: "html",
                    success: function (result) {
                        modalBody.empty();
                        modalBody.append(result);
                        $('#modalReplace').modal('show');
                    }
                });
            });

            //PRODUCT REMOVE
            $(".btn-rem").click(function () {
                var trLineId = $(this).closest("tr").attr('id');

                $.ajax({
                    url: "/SupplierOrder/Remove",
                    data: { id: trLineId },
                    cache: false,
                    type: "get",
                    dataType: "html",
                    success: function (result) {
                        location.reload();
                    }
                });
            });

        });


    </script>

    <script src="~/Areas/Admin/Content/vendors/pnotify/dist/pnotify.js"></script>
}

Areas/Admin/Views/SupplierOrder/ProductNewQuantity.cshtml
@model Suppliro.Areas.Admin.ViewModels.ProductNewQuantity

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="myModalLabel">Replace Quantity</h4>
</div>

@using (Html.BeginForm("ProductNewQuantity", "SupplierOrder", FormMethod.Post, new { @id = "frmProductNewQuantity", @name = "frmProductNewQuantity" }))
{
    <div class="modal-body">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12 md-margin">

                @Html.HiddenFor(Model => Model.iSupplierOrderID)
                @Html.HiddenFor(Model => Model.iSupplierOrderLineID)
                @Html.HiddenFor(Model => Model.strProductName)

                <header class="content-title">
                    <div class="title-bg">
                        <h1 class="prod-id">@Model.strProductName</h1>
                    </div><!-- End .title-bg -->
                </header>
                <div class="form-group">
                    <label for="iProductQuantity">New Quantity (Qty)</label><br />
                    @Html.EditorFor(Model => Model.iProductQuantity, new { htmlAttributes = new { @placeholder = "0" } })
                    @Html.ValidationMessageFor(Model => Model.iProductQuantity)
                </div>
                <label id="lblValidationMessage" style="display:none; color:red;"></label>
                <div class="lg-margin2x"></div>
            </div>
        </div>
    </div>

    <div class="modal-footer">
        <button class="btn" data-dismiss="modal">Cancel</button>
        <input id="btnSubmit" class="btn btn-primary" value="Replace" onclick="submitForm()" />
    </div>
}

@****SUBMIT ITEM****@
<script type="text/javascript">
    function submitForm() {
        var iQuantity = $('#iProductQuantity').val();
        var iSupplierOrderID = $('#iSupplierOrderID').val();

        if (iQuantity > 0)
        {
            var message = "";
            $('#lblValidationMessage').hide();
            $('#lblValidationMessage').text(message);
            $("#frmProductNewQuantity").submit();

            var modalBody = $("#modalProductQuantityContent");
            var modal = $('#modalProductQuantity');
            modalBody.empty();
            modal.modal('toggle');

            //window.location.href = "/Admin/Home/Index/";
            location.reload();
            //window.location.href = "/Admin/SupplierOrder/Order/" + iSupplierOrderID.toString() + "/";
        }
        else
        {
            var message = "No Quantity Specified";
            $('#lblValidationMessage').show();
            $('#lblValidationMessage').text(message);
        }

        }
</script>

@****PRODUCT CATEGORY SELECT****@
<script type="text/javascript">
    function jsProductCategoryListSelect() {
        var iSelectedProductCategory = $("#lstProductCategoryList option:selected").val();

        if (iSelectedProductCategory > 0)
        {
            $.ajax({
                url: '@Url.Action("ProductReplaceCategoryChange", "SupplierOrder")',
                type: "POST",
                data: {"iSelectedProductCategory": iSelectedProductCategory},
                success: function (products) {

                    // states is your JSON array
                    $('#iQuantity').val("0");
                    //Populate Product List
                    $("#lstProductList").html("");

                    $.each(products.lstProducts, function (i, item) {
                        $("#lstProductList").append(
                    $('<option></option>').val(item.Id).html(item.DisplayName));
                    });
                }
            });
        }

        }
</script>