Entities/Supplier.cs
using Suppliro.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Suppliro.Entities
{
    public class Supplier
    {
        [Key]
        public int Id { get; set; }

        public string UserId { get; set; }

        [ForeignKey("UserId")]
        public ApplicationUser User { get; set; }

        [Display(Name = "Trading Name")]
        public string TradingName { get; set; }

        [Required]
        [Display(Name = "Registered Name")]        
        public string RegisteredName { get; set; }

        [Display(Name = "VAT Number")]
        public string VATNumber { get; set; }

        [Display(Name = "Tel Number")]
        public string TelNumber { get; set; }

        [Display(Name = "Cellphone")]
        public string CellNumber { get; set; }

        public bool HasCredit { get; set; }

        [Required]
        [Display(Name = "Email")]
        public string EmailAddress { get; set; }
                
        [Display(Name = "Fax")]
        public string FaxNumber { get; set; }

        public bool IsActive { get; set; }

        #region Physical Address
        [Display(Name = "Physical Address")]
        public string PhysicalAddress1 { get; set; }

        [Display(Name = "Physical Address")]
        public string PhysicalAddress2 { get; set; }

        [Display(Name = "Postal Code")]
        public string PhysicalPostalCode { get; set; }

        [Display(Name = "Region")]
        public string PhysicalRegion { get; set; }

        [Display(Name = "City")]
        public string PhysicalTown { get; set; }

        #endregion

        #region Postal Address
        [Display(Name = "Postal Address")]
        public string PostalAddress1 { get; set; }

        [Display(Name = "Physical Address")]
        public string PostalAddress2 { get; set; }

        [Display(Name = "Postal Code")]
        public string PostalPostalCode { get; set; }

        [Display(Name = "Region")]
        public string PostalRegion { get; set; }

        [Display(Name = "City")]
        public string PostalTown { get; set; }

        #endregion
    }
}

Areas/Admin/Controllers/SupplierController.cs
using Suppliro.Areas.Admin.Manager;
using Suppliro.Context;
using Suppliro.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Suppliro.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class SupplierController : Controller
    {
        // GET: Admin/Supplier
        public ActionResult Index()
        {
            SupplierManager _mgr = new SupplierManager(new DBContext());
            return View(_mgr.GetAllSuppliers());
        }

        public ActionResult Edit(int? id)
        {
            SupplierManager _mgr = new SupplierManager(new DBContext());
            return View(_mgr.GetSupplier(id));
        }

        public ActionResult Add(Supplier model)
        {
            if (!ModelState.IsValid)
            {
                return View("Edit", model);
            }

            SupplierManager _mgr = new SupplierManager(new DBContext());
            model = _mgr.AddSupplier(model);
            return View("Edit", model);
        }
    }
}

Areas/Admin/Views/Supplier/Edit.cshtml
@model Suppliro.Entities.Supplier

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_layoutAdmin.cshtml";
}

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                @{
                    if (Model.Id == 0)
                    {
                        <h1>Add Supplier</h1>
                    }
                    else
                    {
                        <h1> Edit </h1>
                    }
                }
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                @using (Html.BeginForm("Add", "Supplier", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                {
                    @Html.HiddenFor(x => x.Id)
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary()
                    <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                            <h2>General Information</h2>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">
                            <label>Do we have credit with this supplier?</label>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            @Html.CheckBoxFor(x => x.HasCredit, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">
                            @Html.LabelFor(m => m.TradingName)
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            @Html.TextBoxFor(m => m.TradingName, new { @class = "form-control col-md-7 col-xs-12", @placeholder = "Trading Name" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">
                            @Html.LabelFor(m => m.RegisteredName)
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            @Html.TextBoxFor(m => m.RegisteredName, new { @class = "form-control col-md-7 col-xs-12", @placeholder = "Registered Name" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">
                            @Html.LabelFor(m => m.VATNumber)
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            @Html.TextBoxFor(m => m.VATNumber, new { @class = "form-control col-md-7 col-xs-12", @placeholder = "VAT Number" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">
                            @Html.LabelFor(m => m.TelNumber)
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            @Html.TextBoxFor(m => m.TelNumber, new { @class = "form-control col-md-7 col-xs-12", @placeholder = "Telephone Number" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">
                            @Html.LabelFor(m => m.CellNumber)
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            @Html.TextBoxFor(m => m.CellNumber, new { @class = "form-control col-md-7 col-xs-12", @placeholder = "Cell Number" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="control-label col-md-3 col-sm-3 col-xs-12">
                        </div>
                        <label class="col-md-6 col-sm-6 col-xs-12">
                            Use ";" to seperate email addresses
                        </label>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">
                            @Html.LabelFor(m => m.EmailAddress)
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            @Html.TextBoxFor(m => m.EmailAddress, new { @class = "form-control col-md-7 col-xs-12", @placeholder = "Email" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">
                            @Html.LabelFor(m => m.FaxNumber)
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            @Html.TextBoxFor(m => m.FaxNumber, new { @class = "form-control col-md-7 col-xs-12", @placeholder = "Fax" })
                        </div>
                    </div>
                    <div class="clearfix"></div>
                    <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                            <h2>Physical Address</h2>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">
                            @Html.LabelFor(m => m.PhysicalAddress1)
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            @Html.TextBoxFor(m => m.PhysicalAddress1, new { @class = "form-control col-md-7 col-xs-12", @placeholder = "Address" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">
                            @Html.LabelFor(m => m.PhysicalAddress2)
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            @Html.TextBoxFor(m => m.PhysicalAddress2, new { @class = "form-control col-md-7 col-xs-12", @placeholder = "Address" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">
                            @Html.LabelFor(m => m.PhysicalPostalCode)
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            @Html.TextBoxFor(m => m.PhysicalPostalCode, new { @class = "form-control col-md-7 col-xs-12", @placeholder = "Postal Code" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">
                            @Html.LabelFor(m => m.PhysicalRegion)
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            @Html.TextBoxFor(m => m.PhysicalRegion, new { @class = "form-control col-md-7 col-xs-12", @placeholder = "Region" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">
                            @Html.LabelFor(m => m.PhysicalTown)
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            @Html.TextBoxFor(m => m.PhysicalTown, new { @class = "form-control col-md-7 col-xs-12", @placeholder = "City" })
                        </div>
                    </div>
                    <div class="clearfix"></div>
                    <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                            <h2>Postal Address</h2>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">
                            @Html.LabelFor(x => x.PostalAddress1)
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            @Html.TextBoxFor(m => m.PostalAddress1, new { @class = "form-control col-md-7 col-xs-12", @placeholder = "Address" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">
                            @Html.LabelFor(x => x.PostalAddress2)
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            @Html.TextBoxFor(m => m.PostalAddress2, new { @class = "form-control col-md-7 col-xs-12", @placeholder = "Address" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">
                            @Html.LabelFor(x => x.PostalPostalCode)
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            @Html.TextBoxFor(m => m.PostalPostalCode, new { @class = "form-control col-md-7 col-xs-12", @placeholder = "Postal Code" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">
                            @Html.LabelFor(x => x.PostalRegion)
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            @Html.TextBoxFor(m => m.PostalRegion, new { @class = "form-control col-md-7 col-xs-12", @placeholder = "Region" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">
                            @Html.LabelFor(x => x.PostalTown)
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            @Html.TextBoxFor(m => m.PostalTown, new { @class = "form-control col-md-7 col-xs-12", @placeholder = "City" })
                        </div>
                    </div>
                    <div class="clearfix"></div>
                    <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                            <button type="submit" class="btn btn-primary">Cancel</button>
                            <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

Areas/Admin/Views/Supplier/Index.cshtml
@model Suppliro.Areas.Admin.ViewModels.SupplierListViewModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_layoutAdmin.cshtml";
}

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Suppliers</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li>
                        <a href="Supplier/Edit" class="collapse-link"><i class="glyphicon glyphicon-plus"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                @{
                    if (Model.Suppliers.Count == 0)
                    {
                        <div class="bs-example" data-example-id="simple-jumbotron">
                            <div class="jumbotron">
                                <h1>No Suppliers Found</h1>
                            </div>
                        </div>
                    }
                    else
                    {
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>Trading Name</th>
                                    <th>Registered Name</th>
                                    <th>VAT Number</th>
                                    <th>Email Address</th>
                                    <th>Edit</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var sup in Model.Suppliers)
                                {
                                <tr>
                                    <td>@sup.TradingName</td>
                                    <td>@sup.RegisteredName</td>
                                    <td>@sup.VATNumber</td>
                                    <td>@sup.EmailAddress</td>
                                    <td>@Html.ActionLink("Edit", "Edit", new { id = @sup.Id })</td>
                                </tr>
                                }
                            </tbody>
                        </table>
                    }
                }
            </div>
        </div>
    </div>
</div>