ViewModels/ShoppingCartViewModel.cs
using Suppliro.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Suppliro.ViewModels
{
    public class ShoppingCartViewModel
    {
        public List<Cart> CartItems { get; set; }

        public double CartTotal { get; set; }
    }
}

Controllers/ShoppingCartController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Suppliro.Context;
using Suppliro.Data;
using Suppliro.Entities;
using Suppliro.Manager;
using Suppliro.Models;
using Suppliro.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Suppliro.Controllers
{
    [Authorize]
    public class ShoppingCartController : Controller
    {
        // GET: ShoppingCart
        public ActionResult Index()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Set up our ViewModel
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal()
            };
            // Return the view
            return View(viewModel);
        }

        // GET: /Store/AddToCart/5
        public ActionResult AddToCart(int id, int count)
        {
            ProductData _productData = new ProductData();
            // Retrieve the product from the database
            var addedProduct = _productData.GetProductById(id);

            // Add it to the shopping cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            cart.AddToCart(addedProduct, count);

            // Go back to the main store page for more shopping
            return RedirectToAction("CartSummary");
        }
        //
        // AJAX: /ShoppingCart/RemoveFromCart/5
        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            CartData _cartData = new CartData();
            // Remove the item from the cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Get the name of the album to display confirmation
            Cart cartItem = _cartData.GetCartItemByRecordId(id);

            string productCode = cartItem.Product.Code;

            // Remove from cart
            _cartData.RemoveCart(cartItem);

            // Display the confirmation message
            var results = new ShoppingCartRemoveViewModel
            {
                Message = Server.HtmlEncode(productCode) +
                    " has been removed from your shopping cart.",
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                DeleteId = id
            };
            return Json(results);
        }
        //
        // GET: /ShoppingCart/CartSummary
        public ActionResult CartSummary()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            ViewData["CartCount"] = cart.GetCount();
            ViewData["CartAmount"] = cart.GetTotal();
            return PartialView("CartSummary");
        }

        public ActionResult CreateOrder()
        {
            var _db = new DBContext();
            var store = new UserStore<ApplicationUser>(_db);
            var userManager = new UserManager<ApplicationUser>(store);
            ApplicationUser user = userManager.FindByName(User.Identity.Name);

            OrderManager ordMgr = new OrderManager(_db);
            ordMgr.BuildOrder(user, ShoppingCart.GetCart(this.HttpContext));

            return RedirectToAction("Index", "Home");
        }
    }
}

Views/ShoppingCart/Index.cshtml
@model Suppliro.ViewModels.ShoppingCartViewModel

@{
    ViewBag.Title = "Cart";
}

<header class="content-title">
    <div class="title-bg">
        <h2 class="title">Cart</h2>
    </div><!-- End .title-bg -->
</header>
<div class="lg-margin"></div>
@{
    if (Model.CartItems == null || Model.CartItems.Count == 0)
    {
        <div class="row">
            <div class="col-lg-12">
                <h2>Your cart is Empty.</h2>
                <div class="lg-margin3x"></div>
            </div>
        </div>
    }
    else
    {
        <div class="row">
            <div class="col-lg-6">
                <h3>
                    Review your cart
                </h3>
            </div>
            <div class="col-lg-6">
                <h3 class="pull-right">
                    Total: @Model.CartTotal
                </h3>
            </div>
        </div>
        <div class="lg-margin"></div>
        <div id="update-message">
        </div>
        <div class="row">
            <div class="col-lg-12">
                <table class="table" id="Cart">
                    <thead>
                        <tr>
                            <th>
                                Code
                            </th>
                            <th>
                                Price (each)
                            </th>
                            <th>
                                Total Price
                            </th>
                            <th>
                                Quantity
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.CartItems)
                        {
                            var prodTotal = @item.Product.MarkedUpPrice * @item.Count;

                            <tr id="row-@item.RecordId">
                                <td>
                                    @item.Product.Code
                                </td>
                                <td>
                                    @item.Product.MarkedUpPrice
                                </td>
                                <td>@prodTotal</td>
                                <td id="item-count-@item.RecordId">
                                    @item.Count
                                </td>
                                <td>
                                    <a href="#" class="RemoveLink" data-id="@item.RecordId">Remove from cart</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
        <div class="lg-margin"></div>
        <div class="row">
            <div class="col-md-offset-3">
                <div class="col-md-8">
                    @Html.ActionLink("Place Order", "CreateOrder", "ShoppingCart", null, new { @class = "btn btn-custom btn-block" })
                </div>
            </div>
        </div>
    }
}

@section scripts{
    <script type="text/javascript">
        //$(function () {
        //    $('#Cart').DataTable({
        //        "paging": true,
        //        "ordering": true
        //    });
        //})

        $(function () {
            // Document.ready -> link up remove event handler
            $(".RemoveLink").click(function () {
                // Get the id from the link
                var recordToDelete = $(this).attr("data-id");
                if (recordToDelete != '') {
                    // Perform the ajax post
                    $.post("/ShoppingCart/RemoveFromCart", { "id": recordToDelete },
                        function (data) {
                            // Successful requests get here
                            // Update the page elements
                            if (data.ItemCount == 0) {
                                $('#row-' + data.DeleteId).fadeOut('slow');
                            } else {
                                $('#item-count-' + data.DeleteId).text(data.ItemCount);
                            }
                            $('#cart-total').text(data.CartTotal);
                            $('#update-message').text(data.Message);
                            $('#cart-status').text('Cart (' + data.CartCount + ')');
                            location.reload();
                        });
                }
            });
        });
    </script>
}