Areas/Admin/ViewModels/ProFormaViewModel.cs
using Suppliro.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Suppliro.Areas.Admin.ViewModels
{
    public class ProFormaViewModel
    {
        public CompanyInformation CompanyInfo { get; set; }

        public Invoice Invoice { get; set; }
    }
}

Areas/Admin/Controllers/InvoiceController.cs
using Suppliro.Areas.Admin.Data;
using Suppliro.Areas.Admin.Models;
using Suppliro.Areas.Admin.ViewModels;
using Suppliro.Context;
using Suppliro.Entities;
using Suppliro.Manager;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Suppliro.Data;

namespace Suppliro.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class InvoiceController : Controller
    {
        // GET: Admin/Invoice
        public ActionResult Index()
        {
            OrderManager ordMgr = new OrderManager(new DBContext());
            return View(ordMgr.GetOrdersCompletedToday());
        }

        /// <summary>
        /// Returns customers with open pro forma invoices
        /// </summary>
        /// <returns></returns>
        public ActionResult Customers()
        {
            InvoiceManager invMgr = new InvoiceManager(new DBContext());
            return View(invMgr.CustomersWithProFormaInvoices());
        }

        public ActionResult DownloadActionAsPDF(int? id)
        {
            OrderManager ordMgr = new OrderManager(new DBContext());
            var model = ordMgr.GetCustomerInvoicesViewModel(id);

            if (model == null || model.Invoices == null)
                return RedirectToAction("Index");

            //Code to get content
            return new Rotativa.ActionAsPdf("InvoicePDF", new { id = id }) { FileName = model.Invoices.FirstOrDefault().OrderNumber + ".pdf" };
        }

        public ActionResult DownloadActionAsPDFEdited(int? id)
        {
            OrderManager ordMgr = new OrderManager(new DBContext());
            OrderData OrderData = new OrderData(new DBContext());

            var model = ordMgr.GetCustomerInvoicesViewModelEdited(id);

            if (model == null || model.Invoices == null || model.Invoices.Count == 0)
                return RedirectToAction("Index");

            List<OrderLineEdited> lstOrderLineEdited = new List<OrderLineEdited>();

            foreach (var item in model.Invoices)
            {
                var lstOrderLineEditedList = OrderData.GetOrderLinesEditedByOrderId(item.Id);
                foreach (var item2 in lstOrderLineEditedList)
                    if (!(lstOrderLineEdited.Any(x => x.Id == item2.Id)))
                        lstOrderLineEdited.Add(item2);
            }

            model.lstOrderLineEditedAdded = new List<OrderLineEdited>();
            model.lstOrderLineEditedRemoved = new List<OrderLineEdited>();
            model.lstOrderLineEditedChanged = new List<OrderLineEdited>();

            foreach (var item in model.Invoices)
            {
                //Compare changes to original order line and order line edited
                if (lstOrderLineEdited.Count > 0 && item.OrderLines.Count > 0)
                {
                    foreach (var item2 in lstOrderLineEdited)
                    {
                        if (item.OrderLines.Any(x => x.Id == item2.OrderLineId))
                        {
                            if (!(model.lstOrderLineEditedAdded.Any(y => y.Id == item2.Id)))
                            {
                                model.lstOrderLineEditedAdded.Add(item2);
                                if (item2.QuantityEdited == true)
                                    model.lstOrderLineEditedChanged.Add(item2);
                            }
                        }
                        else
                        {
                            if (!(model.lstOrderLineEditedRemoved.Any(y => y.Id == item2.Id)))
                                model.lstOrderLineEditedRemoved.Add(item2);
                        }
                    }
                }
            }

            //Code to get content
            return new Rotativa.ActionAsPdf("InvoicePDFEdited", new { id = id }) { FileName = model.Invoices.FirstOrDefault().OrderNumber + ".pdf" };
        }

        [AllowAnonymous]
        public ActionResult InvoicePDF(int? id)
        {
            OrderManager ordMgr = new OrderManager(new DBContext());
            var model = ordMgr.GetCustomerInvoicesViewModel(id);

            return View(model);
        }

        [AllowAnonymous]
        public ActionResult InvoicePDFEdited(int? id)
        {
            OrderManager ordMgr = new OrderManager(new DBContext());
            OrderData OrderData = new OrderData(new DBContext());

            var model = ordMgr.GetCustomerInvoicesViewModelEdited(id);

            List<OrderLineEdited> lstOrderLineEdited = new List<OrderLineEdited>();

            foreach (var item in model.Invoices)
            {
                var lstOrderLineEditedList = OrderData.GetOrderLinesEditedByOrderId(item.Id);
                foreach (var item2 in lstOrderLineEditedList)
                    if (!(lstOrderLineEdited.Any(x => x.Id == item2.Id)))
                        lstOrderLineEdited.Add(item2);
            }

            model.lstOrderLineEditedAdded = new List<OrderLineEdited>();
            model.lstOrderLineEditedRemoved = new List<OrderLineEdited>();
            model.lstOrderLineEditedChanged = new List<OrderLineEdited>();

            foreach (var item in model.Invoices)
            {
                //Compare changes to original order line and order line edited
                if (lstOrderLineEdited.Count > 0 && item.OrderLines.Count > 0)
                {
                    foreach (var item2 in lstOrderLineEdited)
                    {
                        if (item.OrderLines.Any(x => x.Id == item2.OrderLineId))
                        {
                            if (!(model.lstOrderLineEditedAdded.Any(y => y.Id == item2.Id)))
                            {
                                model.lstOrderLineEditedAdded.Add(item2);
                                if (item2.QuantityEdited == true)
                                    model.lstOrderLineEditedChanged.Add(item2);
                            }
                        }
                        else
                        {
                            if (!(model.lstOrderLineEditedRemoved.Any(y => y.Id == item2.Id)))
                                model.lstOrderLineEditedRemoved.Add(item2);
                        }
                    }
                }
            }

            return View(model);
        }

        public ActionResult MakrInvoiced(int id)
        {
            OrderManager ordMgr = new OrderManager(new DBContext());
            ordMgr.MarkOrderAsInvoiced(id);
            return RedirectToAction("Index");
        }

        public ActionResult History()
        {
            OrderManager ordMgr = new OrderManager(new DBContext());
            return View(ordMgr.GetOrdersInvoiced(null));
        }

        public ActionResult HistoryAsPDF(int? id)
        {
            OrderManager ordMgr = new OrderManager(new DBContext());
            var model = ordMgr.GetnvoicedViewModel(id);

            //Code to get content
            return new Rotativa.ActionAsPdf("HistoryPDF", new { id = id }) { FileName = model.Invoices.FirstOrDefault().OrderNumber + ".pdf" };
        }

        [AllowAnonymous]
        public ActionResult HistoryPDF(int? id)
        {
            OrderManager ordMgr = new OrderManager(new DBContext());
            var model = ordMgr.GetnvoicedViewModel(id);

            return View(model);
        }

        public ActionResult ProFormas()
        {
            InvoiceManager mgr = new InvoiceManager(new DBContext());
            return View(mgr.GetInvoicesCompletedToday());
        }

        public ActionResult MarkComplete(int id)
        {
            InvoiceManager mgr = new InvoiceManager(new DBContext());
            mgr.MarkComplete(id);

            return RedirectToAction("ProFormas");
        }

        public ActionResult ProformaAsPDF(int id)
        {
            InvoiceManager mgr = new InvoiceManager(new DBContext());
            var model = mgr.GetProFormaViewModel(id);
            //Code to get content
            return new Rotativa.ActionAsPdf("ProformaPDF", new { id = id }) { FileName = model.Invoice.CustomerTradingName + ".pdf" };
        }

        [AllowAnonymous]
        public ActionResult ProformaPDF(int id)
        {
            InvoiceManager mgr = new InvoiceManager(new DBContext());

            return View(mgr.GetProFormaViewModel(id));
        }

        /// <summary>
        /// Returns pro forma for particular customer
        /// </summary>
        /// <param name="id">Customer Id</param>
        /// <returns></returns>
        public ActionResult Proforma(int id)
        {
            InvoiceManager mgr = new InvoiceManager(new DBContext());
            return View(mgr.GetInvoiceById(id));
        }

        public ActionResult ProFormaHistory()
        {
            InvoiceManager mgr = new InvoiceManager(new DBContext());
            return View(mgr.GetClosedInvoices());
        }
    }
}

Controllers/CustomerController.cs
using Suppliro.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using Suppliro.ViewModels;
using Suppliro.Manager;
using Microsoft.AspNet.Identity.EntityFramework;
using Suppliro.Models;
using Suppliro.Context;
using Microsoft.AspNet.Identity;
using Suppliro.Areas.Admin.ViewModels;
using Suppliro.Areas.Admin.Data;

namespace Suppliro.Controllers
{
    [Authorize]
    public class CustomerController : Controller
    {
        // GET: Customer
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Information()
        {
            var context = new DBContext();
            CustomerManager mgr = new CustomerManager(context);
            var store = new UserStore<ApplicationUser>(context);
            var userManager = new UserManager<ApplicationUser>(store);
            ApplicationUser user = userManager.FindById(User.Identity.GetUserId());

            var customer = mgr.GetCustomerByUserId(user.Id);

            return PartialView(customer);
        }

        [HttpPost]
        public ActionResult SaveInformation(Customer model)
        {
            var context = new DBContext();
            CustomerManager mgr = new CustomerManager(context);
            var store = new UserStore<ApplicationUser>(context);
            var userManager = new UserManager<ApplicationUser>(store);
            ApplicationUser user = userManager.FindById(User.Identity.GetUserId());
            mgr.SaveInformation(model, user.Id);
            return PartialView("Information");
        }

        public ActionResult Address()
        {
            var context = new DBContext();
            CustomerManager mgr = new CustomerManager(context);
            var store = new UserStore<ApplicationUser>(context);
            var userManager = new UserManager<ApplicationUser>(store);
            ApplicationUser user = userManager.FindById(User.Identity.GetUserId());

            return PartialView(mgr.GetCustomerByUserId(user.Id));
        }

        [HttpPost]
        public ActionResult SaveAddress(Customer model)
        {
            var context = new DBContext();
            CustomerManager mgr = new CustomerManager(context);
            var store = new UserStore<ApplicationUser>(context);
            var userManager = new UserManager<ApplicationUser>(store);
            ApplicationUser user = userManager.FindById(User.Identity.GetUserId());
            mgr.SaveAddress(model, user.Id);
            return PartialView("Address");
        }

        public ActionResult Invoice()
        {
            var context = new DBContext();
            CustomerManager mgr = new CustomerManager(context);
            InvoiceManager invMgr = new InvoiceManager(context);
            var store = new UserStore<ApplicationUser>(context);
            var userManager = new UserManager<ApplicationUser>(store);
            ApplicationUser user = userManager.FindById(User.Identity.GetUserId());
            var customer = mgr.GetCustomerByUserId(user.Id);

            var invoice = invMgr.GetInvoice(customer.Id) ?? new Invoice();

            return PartialView(invoice);
        }

        public ActionResult InvoiceHistory(string currentFilter, string searchString, int? page)
        {
            var context = new DBContext();
            CustomerManager mgr = new CustomerManager(context);
            InvoiceManager invMgr = new InvoiceManager(context);
            var store = new UserStore<ApplicationUser>(context);
            var userManager = new UserManager<ApplicationUser>(store);
            ApplicationUser user = userManager.FindById(User.Identity.GetUserId());
            var customer = mgr.GetCustomerByUserId(user.Id);

            if (searchString != null)
                page = 1;
            else
                searchString = currentFilter;

            ViewBag.CurrentFilter = searchString;

            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return PartialView(invMgr.GetInvoicesByCustomerIdPaged(customer.Id, pageNumber, pageSize));
        }

        public ActionResult Invoices(string currentFilter, string searchString, int? page)
        {
            var context = new DBContext();
            CustomerManager mgr = new CustomerManager(context);
            OrderManager ordMgr = new OrderManager(context);
            var store = new UserStore<ApplicationUser>(context);
            var userManager = new UserManager<ApplicationUser>(store);
            ApplicationUser user = userManager.FindById(User.Identity.GetUserId());
            var customer = mgr.GetCustomerByUserId(user.Id);

            if (searchString != null)
                page = 1;
            else
                searchString = currentFilter;

            ViewBag.CurrentFilter = searchString;

            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return PartialView(ordMgr.GetOrdersByCustomerId(customer.Id, pageNumber, pageSize));
        }

        [HttpGet]
        public ActionResult UpdatePassword()
        {
            return PartialView();
        }

        [HttpPost]
        public ActionResult UpdatePassword(PasswordModel model)
        {
            if (model != null && !string.IsNullOrWhiteSpace(model.Password))
            {
                var context = new DBContext();
                var store = new UserStore<ApplicationUser>(context);
                var userManager = new UserManager<ApplicationUser>(store);
                ApplicationUser user = userManager.FindById(User.Identity.GetUserId());

                userManager.RemovePassword(user.Id);
                userManager.AddPassword(user.Id, model.Password);

                context.SaveChanges();
            }

            return PartialView("UpdatePassword");
        }

        public ActionResult OrderLines(int id)
        {
            var context = new DBContext();
            CustomerManager mgr = new CustomerManager(context);
            OrderManager ordMgr = new OrderManager(context);
            var store = new UserStore<ApplicationUser>(context);
            var userManager = new UserManager<ApplicationUser>(store);
            ApplicationUser user = userManager.FindById(User.Identity.GetUserId());
            var customer = mgr.GetCustomerByUserId(user.Id);

            return PartialView(ordMgr.GetCustomerOrderViewModel(id, customer.Id));
        }

        public ActionResult CustomerInvoice(int id)
        {
            var context = new DBContext();
            CustomerManager mgr = new CustomerManager(context);
            InvoiceManager invMgr = new InvoiceManager(context);

            return PartialView("InvoicePartial", invMgr.GetInvoiceById(id));
        }

        public ActionResult DownloadInvoiceAsPDF(int id)
        {
            InvoiceManager mgr = new InvoiceManager(new DBContext());
            var model = mgr.GetInvoiceById(id);

            //Code to get content
            return new Rotativa.ActionAsPdf("InvoicePDF", new { id = id }) { FileName = model.InvoiceNumber + ".pdf" };
        }

        [AllowAnonymous]
        public ActionResult InvoicePDF(int id)
        {
            InvoiceManager mgr = new InvoiceManager(new DBContext());
            return View("~/Areas/Admin/Views/Invoice/ProFormaPDF.cshtml", mgr.GetProFormaViewModel(id));
        }

        public ActionResult DownloadOrderAsPDF(int id)
        {
            OrderManager mgr = new OrderManager(new DBContext());
            var model = mgr.GetOrderById(id);

            //Code to get content
            return new Rotativa.ActionAsPdf("OrderPDF", new { id = id }) { FileName = model.OrderNumber + ".pdf" };
        }

        [AllowAnonymous]
        public ActionResult OrderPDF(int id)
        {
            var context = new DBContext();

            OrderManager mgr = new OrderManager(context);
            CompanyInformationData ciData = new CompanyInformationData(context);

            var invoiceList = new List<Order>();
            invoiceList.Add(mgr.GetOrderById(id));

            CustomerInvoicesViewModel vm = new CustomerInvoicesViewModel
            {
                CompanyInfo = ciData.GetInformation(),
                Invoices = invoiceList
            };

            return View("~/Areas/Admin/Views/Invoice/InvoicePDF.cshtml", vm);
        }
    }
}

Areas/Admin/Views/Invoice/History.cshtml
@model List<Suppliro.Entities.Order>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_layoutAdmin.cshtml";
}

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            @{
                if (Model == null || Model.Count == 0)
                {
                    <div class="bs-example" data-example-id="simple-jumbotron">
                        <div class="jumbotron">
                            <h1>No invoiced orders found</h1>
                        </div>
                    </div>
                }
                else
                {
                    <div class="x_title">
                        <h2>Invoiced Orders</h2>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <table class="table table-striped" id="Suppliers">
                            <thead>
                                <tr>
                                    <th>
                                        Order Number
                                    </th>
                                    <th>
                                        Customer
                                    </th>
                                    <th>
                                        Date Created
                                    </th>
                                    <th>
                                        Date Completed
                                    </th>
                                    <th style="width: 50px;">Download</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model != null && Model.Count > 0)
                                {
                                    foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>
                                                @item.OrderNumber
                                            </td>
                                            <td>
                                                @item.CustomerName
                                            </td>
                                            <td>
                                                @item.DatePlaced
                                            </td>
                                            <td>
                                                @item.DateCompleted
                                            </td>
                                            <td style="min-width: 25px">
                                                @Html.ActionLink("Download", "HistoryAsPDF", "Invoice", new { id = item.Id }, new { @id = item.Id, @class = "btn btn-primary viewclick" })
                                            </td>
                                        </tr>
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                }
            }
        </div>
    </div>
</div>

Areas/Admin/Views/Invoice/Index.cshtml
@model List<Suppliro.Entities.Order>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_layoutAdmin.cshtml";
}


<div class="page-title">
    <div class="title_left">
        <h3>
            Order Handling
        </h3>
    </div>
</div>

<div class="clearfix"></div>

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            @{
                if (Model == null || Model.Count == 0)
                {
                    <div class="bs-example" data-example-id="simple-jumbotron">
                        <div class="jumbotron">
                            <h1>No orders found to be invoiced</h1>
                        </div>
                    </div>
                }
                else
                {
                    <div class="x_title">
                        <h2>Customers with open Invoices</h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        @Html.ActionLink("Download Invoices", "DownloadActionAsPDF", "Invoice", null, null)
                                    </li>
                                </ul>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <table class="table table-striped" id="Suppliers">
                            <thead>
                                <tr>
                                    <th>
                                        Order Number
                                    </th>
                                    <th>
                                        Customer
                                    </th>
                                    <th>
                                        Date Placed
                                    </th>
                                    <th style="width: 150px;">Mark as Invoiced</th>
                                    <th style="width: 50px;">Download</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model != null && Model.Count > 0)
                                {
                                    foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>
                                                @item.OrderNumber
                                            </td>
                                            <td>
                                                @item.CustomerName
                                            </td>
                                            <td>
                                                @item.DatePlaced
                                            </td>
                                            <td style="min-width: 25px">
                                                @Html.ActionLink("Mark Invoiced", "MakrInvoiced", "Invoice", new { id = item.Id }, new { @id = item.Id, @class = "btn btn-primary viewclick" })
                                            </td>
                                            <td style="min-width: 50px">
                                                @if (item.IsInvoiced)
                                                {
                                                    @*@Html.ActionLink("Download", "DownloadActionAsPDF", "Invoice", new { id = item.Id }, new { @id = item.Id, @class = "btn btn-primary viewclick" })*@
                                                    @Html.ActionLink("Download", "DownloadActionAsPDFEdited", "Invoice", new { id = item.Id }, new { @id = item.Id, @class = "btn btn-primary viewclick" })
                                                }
                                                else
                                                {
                                                    @Html.Raw("Not Finalized");
                                                }
                                            </td>
                                        </tr>
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                }
            }
        </div>
    </div>
</div>

Areas/Admin/Views/Invoice/ProFormaHistory.cshtml
@model List<Suppliro.Entities.Invoice>

@{
    ViewBag.Title = "ProFormas";
    Layout = "~/Areas/Admin/Views/Shared/_layoutAdmin.cshtml";
}

<div class="page-title">
    <div class="title_left">
        <h3>
            Pro Forma Invoices
        </h3>
    </div>
</div>

<div class="clearfix"></div>

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Open Pro Forma Invoices</h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                @{
                    if (Model == null || Model.Count == 0)
                    {
                        <div class="bs-example" data-example-id="simple-jumbotron">
                            <div class="jumbotron">
                                <h1>No open Pro Forma Invoices</h1>
                            </div>
                        </div>
                    }
                    else
                    {
                        <table class="table table-striped" id="Suppliers">
                            <thead>
                                <tr>
                                    <th>
                                        Customer
                                    </th>
                                    <th>
                                        Invoice Number
                                    </th>
                                    <th>
                                        Date Created
                                    </th>
                                    <th>
                                        Date Completed
                                    </th>
                                    <th>
                                        Sub Total
                                    </th>
                                    <th>
                                        Vat
                                    </th>
                                    <th>
                                        Total
                                    </th>
                                    <th style="width: 50px;">View</th>
                                    <th style="width: 50px;">Download</th>
                                </tr>
                            </thead>
                            <tbody>
                                @{
                                    foreach (var invoice in Model)
                                    {
                                        <tr>
                                            <td>
                                                @invoice.CustomerTradingName
                                            </td>
                                            <td>
                                                @invoice.InvoiceNumber
                                            </td>
                                            <td>
                                                @invoice.DateCreated
                                            </td>
                                            <td>
                                                @invoice.DateCompleted
                                            </td>
                                            <td>
                                                @invoice.SubTotalAmount
                                            </td>
                                            <td>
                                                @invoice.VATAmount
                                            </td>
                                            <td>
                                                @invoice.TotalAmount
                                            </td>
                                            <td style="min-width: 25px">
                                                @Html.ActionLink("View", null, null, new { @id = invoice.Id, @class = "btn btn-primary viewclick" })
                                            </td>
                                            <td style="min-width: 25px">
                                                @Html.ActionLink("Download", "ProformaAsPDF", "Invoice", new { id = invoice.Id }, new { @id = invoice.Id, @class = "btn btn-primary" })
                                            </td>
                                        </tr>
                                    }
                                }
                            </tbody>
                        </table>
                                    }
                }
            </div>
        </div>
    </div>
</div>

<div class="row proforma">

</div>

@section scripts{
    <script type="text/javascript">
        $('.viewclick').click(function (e) {
            e.preventDefault()

            var id = $(this).attr("id");

            $(".proforma").empty().append("<div class='loader'><img src='/Content/img/Loader/ajax-loader.gif' alt='Loading' /></div>");

            $.ajax({
                url: "@Url.Action("Proforma", "Invoice")",
                data: { id: id },
                cache: false,
                type: "get",
                dataType: "html",
                success: function (result) {
                    $(".proforma").empty().append(result);
                }
            });
        });
    </script>
}